const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
test('guided tour requires decisions, exports the chosen demo copy, and restarts independently',async()=>{
 class Element{constructor(){this.children=[];this.events={};this.attrs={};this.textContent='';}addEventListener(name,fn){this.events[name]=fn;}append(...nodes){this.children.push(...nodes);}replaceChildren(){this.children=[];}setAttribute(key,value){this.attrs[key]=value;}focus(){}click(){this.events.click?.();}remove(){}}
 const html=fs.readFileSync(path.join(__dirname,'../extension/tour.html'),'utf8'),nodes=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));const body=new Element(),blobs=[];
 const ctx={BeforeYouSendScanner:require('../extension/scanner.js'),BeforeYouSendReview:require('../extension/review-core.js'),document:{getElementById:id=>nodes[id],createElement:()=>new Element(),body},Blob,URL:{createObjectURL:b=>{blobs.push(b);return 'blob:demo';},revokeObjectURL(){}},setTimeout(){}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../extension/tour.js'),'utf8'),ctx);
 nodes['tour-next'].click();assert.match(nodes['tour-step'].textContent,/2 of 4/);nodes['tour-next'].click();assert.equal(nodes['tour-next'].disabled,true);nodes['tour-next'].click();assert.match(nodes['tour-step'].textContent,/3 of 4/);
 const findButtons=()=>nodes['tour-findings'].children.flatMap(card=>card.children[2].children);
 findButtons().find(b=>b.attrs['aria-label']==='Redact demo finding 1').click();findButtons().find(b=>b.attrs['aria-label']==='Keep intentionally demo finding 2').click();assert.equal(nodes['tour-next'].disabled,false);nodes['tour-next'].click();assert.match(nodes['tour-output'].textContent,/password="\[REDACTED\]"/);assert.match(nodes['tour-output'].textContent,/tour@example.com/);nodes['tour-download'].click();assert.equal(await blobs[0].text(),nodes['tour-output'].textContent);assert.equal(body.children[0].download,'fictional-tour.redacted.txt');nodes['tour-restart'].click();assert.match(nodes['tour-step'].textContent,/1 of 4/);assert.equal(nodes['tour-output'].hidden,true);
});
