'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const scanner=require('../extension/scanner.js'),core=require('../extension/review-core.js');
function setup(importer=require('../extension/importer.js'),powerup){
 class Element{
 constructor(tag='div'){this.tag=tag;this.value='';this.textContent='';this.children=[];this.events={};this.attrs={};this.hidden=false;this.disabled=false;this.className='';}
 addEventListener(k,fn){this.events[k]=fn;}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}focus(){}scrollIntoView(){}remove(){}click(){this.clicked=true;this.events.click?.();}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 querySelectorAll(selector){const matches=e=>selector.startsWith('.')?e.className.split(' ').includes(selector.slice(1)):selector.startsWith('[')?e.attrs[selector.match(/^\[([^=]+)/)[1]]===selector.match(/="(.*)"\]/)[1]:e.tag===selector;return this.children.flatMap(c=>typeof c==='object'?[...(matches(c)?[c]:[]),...c.querySelectorAll(selector)]:[]);}
 }
 const html=fs.readFileSync(path.join(__dirname,'../extension/workspace.html'),'utf8'),nodes=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));nodes.profile.value='strict';const workers=[],timers=new Map(),blobs=[];let ti=0,clip='';
 class Worker{constructor(){workers.push(this);}postMessage(data){this.data=data;}terminate(){this.terminated=true;}finish(){this.onmessage?.({data:{result:require('../extension/custom-rules.js').scan(scanner,this.data.text,this.data)}});}}
 const body=new Element('body');const ctx={BeforeYouSendPowerup:powerup,BeforeYouSendCustom:require('../extension/custom-rules.js'),BeforeYouSendExamples:require('../extension/examples.js'),BeforeYouSendScanner:scanner,BeforeYouSendImporter:importer,BeforeYouSendReview:core,document:{getElementById:id=>nodes[id],createElement:tag=>new Element(tag),createTextNode:s=>s,body},Worker,Blob,URL:{createObjectURL:blob=>{blobs.push(blob);return 'blob:test';},revokeObjectURL(){}},setTimeout:fn=>{timers.set(++ti,fn);return ti;},clearTimeout:id=>timers.delete(id),window:{addEventListener(){}},navigator:{clipboard:{writeText:async text=>{clip=text;}}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../extension/workspace.js'),'utf8'),ctx);
 return{nodes,workers,blobs,body,ctx,timers,clip:()=>clip,click:id=>nodes[id].events.click(),input:text=>{nodes.draft.value=text;nodes.draft.events.input();},decision:(i,value)=>nodes.findings.querySelector(`[aria-label="${value} finding ${i}"]`).click()};
}
test('every finding starts pending; export requires explicit decisions',()=>{const a=setup();a.input('password=DEMO; alex@example.com');a.click('scan');a.workers[0].finish();assert.match(a.nodes['review-count'].textContent,/2 remaining/);assert.equal(a.nodes.download.disabled,true);a.decision(1,'Redact');assert.equal(a.nodes.download.disabled,true);a.decision(2,'Keep intentionally');assert.equal(a.nodes.download.disabled,false);assert.equal(a.nodes['redacted-preview'].textContent,'password=[REDACTED]; alex@example.com');});
test('download produces a distinct plain-text file containing exactly the comparison output',async()=>{const a=setup();a.input('password=DEMO');a.click('scan');a.workers[0].finish();a.click('redact-all');a.click('download');assert.equal(a.body.children[0].download,'message.redacted.txt');assert.equal(await a.blobs[0].text(),'password=[REDACTED]');assert.equal(a.nodes.draft.value,'password=DEMO');});
test('line viewer pages and Show in code navigates to distant finding',()=>{const a=setup();a.input('normal line\n'.repeat(300)+'password=DEMO');a.click('scan');a.workers[0].finish();assert.match(a.nodes['line-window'].textContent,/1–250/);a.nodes.findings.querySelector('[aria-label="Show finding 1 in code"]').click();assert.match(a.nodes['line-window'].textContent,/251–301/);assert.ok(a.nodes.code.querySelector('.target-line'));});
test('multiline comparison redacts whole span',()=>{const a=setup();a.input('password="one\ntwo"\nend');a.click('scan');a.workers[0].finish();a.click('redact-all');assert.equal(a.nodes['redacted-preview'].textContent,'password="[REDACTED]"\nend');});
test('edit invalidates decisions, export and delayed scan results',()=>{const a=setup();a.input('password=OLD');a.click('scan');const late=a.workers[0].onmessage;a.input('new text');late({data:{result:scanner.scan('password=OLD')}});assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes.download.disabled,true);});
test('incomplete scans cannot be exported even after redact all',()=>{const a=setup();a.input(Array.from({length:201},(_,i)=>`u${i}@example.com`).join('\n'));a.click('scan');a.workers[0].finish();a.click('redact-all');assert.equal(a.nodes.download.disabled,true);a.click('download');assert.equal(a.blobs.length,0);});
test('keeping all findings is explicit and retains original content in output',()=>{const a=setup();a.input('password=DEMO');a.click('scan');a.workers[0].finish();a.decision(1,'Keep intentionally');assert.equal(a.nodes.download.disabled,false);assert.match(a.nodes['compare-summary'].textContent,/No replacements/);assert.equal(a.nodes['redacted-preview'].textContent,a.nodes.draft.value);});
test('clipboard receives the reviewed output',async()=>{const a=setup();a.input('password=DEMO');a.click('scan');a.workers[0].finish();a.click('redact-all');await a.click('copy');assert.equal(a.clip(),'password=[REDACTED]');});
test('category descriptions distinguish passwords from API keys',()=>{for(const [text,expected] of [['DB_PASSWORD="DEMO"','Password'],['API_KEY="DEMO"','API key / secret key']]){const f=scanner.scan(text).findings[0];assert.equal(core.describe(f,text).category,expected);}});
test('filenames do not preserve path traversal or executable extension',()=>{assert.equal(core.exportName('../../evil.exe'),'evil.exe.redacted.txt');assert.equal(core.exportName('my code.js'),'my_code.js.redacted.txt');});
test('line calculation retains CRLF and handles Unicode offsets',()=>{const text='🔒\r\npassword=DEMO';assert.deepEqual(core.lineStarts(text),[0,4]);assert.equal(core.lineAt(core.lineStarts(text),4),1);});
test('unknown decision does not count as reviewed',()=>{assert.equal(core.canExport([{id:0}],new Map([[0,'unknown']]),true),false);assert.equal(core.canExport([],new Map(),false),false);});
function content(node){return typeof node==='string'?node:(node.textContent||'')+node.children.map(content).join('');}
test('undo restores mixed decisions after redact all, then restores pending',()=>{const a=setup();a.input('password=DEMO; alex@example.com');a.click('scan');a.workers[0].finish();a.decision(1,'Keep intentionally');a.click('redact-all');assert.equal(a.nodes.download.disabled,false);a.click('undo-decision');assert.match(a.nodes['review-count'].textContent,/1 remaining · 0 redact · 1 keep/);assert.equal(a.nodes.download.disabled,true);a.click('undo-decision');assert.match(a.nodes['review-count'].textContent,/2 remaining/);assert.equal(a.nodes['undo-decision'].disabled,true);});
test('editing clears undo history; previous file decisions cannot be restored',()=>{const a=setup();a.input('password=DEMO');a.click('scan');a.workers[0].finish();a.click('redact-all');a.input('password=NEW');a.click('undo-decision');assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes['undo-decision'].disabled,true);});
test('combined category/decision/search filters do not remove hidden export requirements',()=>{const a=setup();a.input('password=DEMO; alex@example.com');a.click('scan');a.workers[0].finish();a.nodes['category-filter'].value='password';a.nodes['category-filter'].events.change();assert.match(a.nodes['filter-count'].textContent,/Showing 1 of 2/);a.decision(1,'Redact');assert.equal(a.nodes.download.disabled,true);a.nodes['decision-filter'].value='pending';a.nodes['decision-filter'].events.change();assert.match(a.nodes['filter-count'].textContent,/Showing 0 of 2/);assert.match(content(a.nodes.findings),/No findings match/);a.nodes['category-filter'].value='all';a.nodes['finding-search'].value='CONTACT';a.nodes['finding-search'].events.input();assert.match(a.nodes['filter-count'].textContent,/Showing 1 of 2/);a.click('redact-all');assert.equal(a.nodes.download.disabled,false);});
test('masking hides source editor and detected values across every review preview, while export honors Keep',async()=>{const a=setup();a.input('password=SECRET_TEST_VALUE');a.nodes['mask-previews'].checked=true;a.nodes['mask-previews'].events.change();a.click('scan');a.workers[0].finish();a.decision(1,'Keep intentionally');assert.equal(a.nodes.draft.hidden,true);for(const id of ['findings','code','original-preview','redacted-preview'])assert.ok(!content(a.nodes[id]).includes('SECRET_TEST_VALUE'),id);assert.match(a.nodes['redacted-preview'].textContent,/\[HIDDEN\]/);await a.click('copy');assert.equal(a.clip(),'password=SECRET_TEST_VALUE');a.nodes.findings.querySelector('[aria-label="Toggle visibility of finding 1"]').click();assert.match(content(a.nodes.findings),/SECRET_TEST_VALUE/);a.click('scan');a.workers[1].finish();assert.ok(!content(a.nodes.findings).includes('SECRET_TEST_VALUE'));});
test('PDF page label comes from metadata and exact source mark receives target style',async()=>{const text='[PDF page 999]\npassword=DEMO';const a=setup({readDetailed:async()=>({text,name:'report.pdf',kind:'pdf',size:300,units:text.length,pageCount:2,pages:[{page:2,start:0,end:text.length}]})});a.nodes['import-file'].files=[{name:'report.pdf'}];await a.nodes['import-file'].events.change();assert.match(a.nodes['extraction-details'].textContent,/2 of 2 pages/);a.click('scan');a.workers[0].finish();assert.match(content(a.nodes.findings),/PDF page 2 · Line/);assert.ok(!content(a.nodes.findings).includes('PDF page 999'));a.nodes.findings.querySelector('[aria-label="Show finding 1 in code"]').click();assert.ok(a.nodes.code.querySelector('.target-mark'));a.input('password=NEW');assert.equal(a.nodes['extraction-summary'].hidden,true);});
test('pasted page-like text cannot create a PDF page reference',()=>{const a=setup();a.input('[PDF page 99]\npassword=DEMO');a.click('scan');a.workers[0].finish();assert.ok(!content(a.nodes.findings).includes('PDF page 99'));});
test('drop accepts one file, reports real extraction progress and rejects multiple files',async()=>{const a=setup({readDetailed:async(file,options)=>{options.onProgress({stage:'Extracting PDF',current:1,total:2});assert.equal(a.nodes['import-meter'].value,1);return{text:'password=DEMO',name:file.name,size:10,units:13,kind:'text',pages:[]};}});const ev=files=>({preventDefault(){},dataTransfer:{files}});await a.nodes['drop-zone'].events.drop(ev([{name:'a.ino'},{name:'b.ino'}]));assert.match(a.nodes.status.textContent,/exactly one/);await a.nodes['drop-zone'].events.drop(ev([{name:'a.ino'}]));assert.equal(a.nodes.draft.value,'password=DEMO');assert.equal(a.nodes['import-meter'].hidden,true);assert.match(a.nodes['import-progress'].textContent,/Import complete/);});
test('failed import preserves draft and old summary; late import cannot overwrite an edit',async()=>{let resolve;const a=setup({readDetailed:()=>new Promise(r=>{resolve=r;})});a.input('original');a.nodes['import-file'].files=[{name:'x.txt'}];const pending=a.nodes['import-file'].events.change();a.input('new edit');resolve({text:'stale import',name:'x.txt',size:10,units:12,kind:'text',pages:[]});await pending;assert.equal(a.nodes.draft.value,'new edit');assert.equal(a.nodes['extraction-summary'].hidden,true);assert.match(a.nodes['import-progress'].textContent,/discarded/);const b=setup({readDetailed:async()=>{throw Error('Damaged file');}});b.input('preserve me');b.nodes['import-file'].files=[{name:'x.pdf'}];await b.nodes['import-file'].events.change();assert.equal(b.nodes.draft.value,'preserve me');assert.match(b.nodes.status.textContent,/Damaged file/);});
test('loading chosen example clears decisions and uses selected content and filename',()=>{const a=setup();a.input('password=OLD');a.click('scan');a.workers[0].finish();a.click('redact-all');a.nodes['example-choice'].value='example-020';a.click('sample');assert.equal(a.nodes.draft.value,require('../extension/examples.js').get('example-020').text);assert.equal(a.nodes.filename.textContent,'example-020.txt');assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes.download.disabled,true);assert.equal(a.nodes['undo-decision'].disabled,true);assert.match(a.nodes.status.textContent,/Arduino mixed config/);});
test('reset a single decision to Pending blocks export and is undoable',()=>{const a=setup();a.input('password=DEMO; demo@example.com');a.click('scan');a.workers[0].finish();a.click('redact-all');a.decision(1,'Reset to Pending');assert.match(a.nodes['review-count'].textContent,/1 remaining · 1 redact/);assert.equal(a.nodes.download.disabled,true);a.click('undo-decision');assert.equal(a.nodes.download.disabled,false);});
test('replacement overrides reach diff, preview and download; undo restores previous output',async()=>{const a=setup();a.input('password=DEMO');a.click('scan');a.workers[0].finish();a.click('redact-all');a.nodes['replacement-style'].value='category';a.nodes['replacement-style'].events.change();assert.equal(a.nodes['redacted-preview'].textContent,'password=[PASSWORD REMOVED]');a.nodes.findings.querySelector('[aria-label="Custom replacement for finding 1"]').value='<PRIVATE>';a.nodes.findings.querySelector('[aria-label="Apply replacement for finding 1"]').click();assert.equal(a.nodes['redacted-preview'].textContent,'password=<PRIVATE>');assert.match(content(a.nodes['difference-preview']),/Removed: DEMO/);assert.match(content(a.nodes['difference-preview']),/Inserted: <PRIVATE>/);a.click('download');assert.equal(await a.blobs[0].text(),'password=<PRIVATE>');a.click('undo-decision');assert.equal(a.nodes['redacted-preview'].textContent,'password=[PASSWORD REMOVED]');});
test('masking hides detected original values in the difference view',()=>{const a=setup();a.input('password=SECRET_DEMO');a.click('scan');a.workers[0].finish();a.nodes['mask-previews'].checked=true;a.nodes['mask-previews'].events.change();assert.ok(!content(a.nodes['difference-preview']).includes('SECRET_DEMO'));assert.match(content(a.nodes['difference-preview']),/\[HIDDEN\]/);});
test('custom terms create findings; changing them invalidates stale results and undo',()=>{const a=setup();a.input('Project ORCHID-7 is confidential');a.nodes['custom-rules'].value='ORCHID-7';a.nodes['custom-rules'].events.input();a.click('scan');a.workers[0].finish();assert.match(content(a.nodes.findings),/Custom confidential term/);a.click('redact-all');assert.equal(a.nodes['redacted-preview'].textContent,'Project [REDACTED] is confidential');a.nodes['custom-rules'].value='NEW-PROJECT';a.nodes['custom-rules'].events.input();assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes.download.disabled,true);assert.equal(a.nodes['undo-decision'].disabled,true);a.nodes['custom-rules'].value='x';a.click('scan');assert.match(a.nodes.status.textContent,/2–128/);assert.equal(a.workers.length,1);});
test('automatic scan is opt-in, debounced, cancellable and rejects a late result',()=>{const a=setup();a.input('password=FIRST');assert.equal(a.timers.size,0);a.nodes['auto-scan'].checked=true;a.nodes['auto-scan'].events.change();a.input('password=SECOND');a.input('password=THIRD');assert.equal(a.timers.size,1);const [id,fn]=[...a.timers][0];a.timers.delete(id);fn();assert.equal(a.workers.length,1);assert.equal(a.workers[0].data.text,'password=THIRD');const late=a.workers[0].onmessage;a.nodes['auto-scan'].checked=false;a.nodes['auto-scan'].events.change();assert.equal(a.workers[0].terminated,true);late({data:{result:scanner.scan('password=THIRD')}});assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes.download.disabled,true);});
test('composition pauses automatic checking and decision changes reset review reminders',()=>{const a=setup();a.nodes['auto-scan'].checked=true;a.nodes.draft.events.compositionstart();a.input('password=DEMO');assert.equal(a.timers.size,0);a.nodes.draft.events.compositionend();assert.equal(a.timers.size,1);a.click('scan');a.workers[0].finish();a.nodes['check-context'].checked=true;a.nodes['check-context'].events.change();assert.match(a.nodes['checklist-status'].textContent,/1 of 3/);a.click('redact-all');assert.equal(a.nodes['check-context'].checked,false);assert.equal(a.nodes.download.disabled,false);});
test('manual scan delays review for power-up and stale animation callback cannot restore edited results',()=>{let finish,starts=0;const powerup={start(){starts++;},cancel(){},finish(callback){finish=callback;}};const a=setup(undefined,powerup);a.input('password=DEMO');a.click('scan');a.workers[0].finish();assert.equal(starts,1);assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes.scan.disabled,true);finish();assert.equal(a.nodes.review.hidden,false);assert.equal(a.nodes.scan.disabled,false);a.click('scan');a.workers[1].finish();const late=finish;a.input('different text');late();assert.equal(a.nodes.review.hidden,true);assert.equal(a.nodes.download.disabled,true);});
test('automatic and incomplete checks do not receive a completion power-up',()=>{let starts=0,finishes=0;const p={start(){starts++;},cancel(){},finish(){finishes++;}};const a=setup(undefined,p);a.nodes['auto-scan'].checked=true;a.input('password=DEMO');const [id,fn]=[...a.timers][0];a.timers.delete(id);fn();a.workers[0].finish();assert.equal(starts,0);assert.equal(finishes,0);assert.equal(a.nodes.review.hidden,false);a.nodes['auto-scan'].checked=false;a.input(Array.from({length:201},(_,i)=>`u${i}@example.com`).join('\n'));a.click('scan');a.workers[1].finish();assert.equal(starts,1);assert.equal(finishes,0);assert.equal(a.nodes.download.disabled,true);});
